### ISSUE TITLE
Feedback Thread

### ISSUE THREAD

**Issue by shenoynikhil** [shenoynikhil/annotated-dimenet#4]
@gasteigerjo I believe the first draft is ready for review. I am extremely grateful to you for agreeing to this.  Also, happy new year!

Please have a look at the [notebook](https://github.com/shenoynikhil/annotated-dimenet/blob/main/dimenet-blog.ipynb) rendered by github. I am still in the process of uploading it to my website and finding a way to render jupyter notebooks as a markdown file.

**Comment by gasteigerjo** [comment]
Done, see my email.

**Comment by shenoynikhil** [comment]
Thanks a lot! I received the email. I'll try to incorporate the changes.
